name: aero

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    env_file: ".env"
    depends_on:
      - app
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  app:
    build: .
    container_name: "aero"
    restart: unless-stopped
    env_file: ".env"
    environment:
      - ORIGIN=$DOMAIN
    expose:
      - 3000
    ports:
      - "3000:3000"

volumes:
  caddy_data:
  caddy_config:
